#!/bin/bash
bspc config border_width            0
bspc config window_gap              10

bspc config split_ratio             0.60
bspc config bottom_padding          0
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc monitor -d . . . . . . . . . .
